### ISSUE TITLE
how to create custom genesis tx for the monero alt-coin fork 

### ISSUE THREAD

**Issue by raza-basit** [moneroexamples/private-testnet#2]
Hi, I hope you are doing very well.

Will you please guide me how to generate new genesis block for the alt-coin fork. 

https://github.com/monero-project/monero/blob/35d5aa36c9b2f4bba169e5947039bf7871649ee1/src/cryptonote_config.h#L160

Thanks

**Comment by moneroexamples** [comment]
The tutorial is rather outdated. Not sure at the moment how it applies to current monero versions. Sorry.
