### ISSUE TITLE
transfer fund from wallet B to wallet C

### ISSUE THREAD

**Issue by kenken64** [moneroexamples/private-testnet#3]
show transfers - > shows the pending out but after it is mined 

the recipient doesn't get the monero unit

kindly help 
refresh
rescan_bc
rescan_spent 

I tried everything!

**Comment by moneroexamples** [comment]
The guide might be outdated. Hadn't had time yet to update it to 0.11.1 version of monero, so maybe this is part of the problem.

**Comment by kenken64** [comment]
I am using the latest version.

Sent from my iPhone

On 13 Mar 2018, at 8:00 AM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


The guide might be outdated. Hadn't had time yet to update it to 0.11.1 version of monero, so maybe this is part of the problem.

**Comment by moneroexamples** [comment]
yep, but the guide was written a while back. Maybe required setup has changed since then.

check if recipent wallet (C) connects to the private network.

**Comment by kenken64** [comment]
How I check that any cli command wallet a and b does work

Sent from my iPhone

On 13 Mar 2018, at 8:49 AM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


yep, but the guide was written a while back. Maybe required setup has changed since then.

check if recipent wallet (C) connects to the private network.

**Comment by moneroexamples** [comment]
you can use `status` command and see if they report up to date height of the blockchain with nodes.

**Comment by kenken64** [comment]
Let me do a video recording and send to you

Sent from my iPhone

On 13 Mar 2018, at 9:17 AM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


you can use status command and see if they report up to date height of the blockchain with nodes.

**Comment by kenken64** [comment]
yes i did use the status command it is pointing to the private network.
________________________________

**Comment by kenken64** [comment]
Here is my recorded video -> https://youtu.be/66ArNI9B5dI
________________________________

**Comment by moneroexamples** [comment]
I get 

> This video has been removed by the user.

**Comment by kenken64** [comment]
https://youtu.be/the4KsD4nvg
________________________________

**Comment by kenken64** [comment]
if the video is too blur then download the mkv https://drive.google.com/file/d/1qsA5c1nesMhW5fIaHMUxVkxyFK_BtMvR/view?usp=sharing
________________________________

**Comment by moneroexamples** [comment]
Can you specify when exactly is the error you are taking about. its almost 10 min video and I don't know what should be looking for.

**Comment by kenken64** [comment]
When I transfer monero  from wallet b/a to d just scroll to the last few minutes of the video. The transfer just disappear and the balance is not deposit to wallet d

Sent from my iPhone

On 13 Mar 2018, at 12:52 PM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you specify when exactly is the error you are taking about. its almost 10 min video and I don't know what should be looking for.

**Comment by kenken64** [comment]
It did show on the transfers log but pending in and out the. Missing deposit

Sent from my iPhone

On 13 Mar 2018, at 12:52 PM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you specify when exactly is the error you are taking about. its almost 10 min video and I don't know what should be looking for.

**Comment by kenken64** [comment]
I use the main net binaries test the same workflow on mainnet it works from my monero wallet to another newly created monero wallet but the fee is killing me usd .50 10

Sent from my iPhone

On 13 Mar 2018, at 12:52 PM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you specify when exactly is the error you are taking about. its almost 10 min video and I don't know what should be looking for.

**Comment by moneroexamples** [comment]
what do you want to do? You dont need private testnet, to use testnet. Just use public testnet network to play around with monero. In private testnet you will be far behind current monero status. You would have to  mine over 1 million blocks to catch up with current monero status, such as having ringct and/or booletproofs.

**Comment by kenken64** [comment]
If it is working on your side can you zip or tar ball the monero binaries and send it to me. The copy of monero binaries that I am using is compile by myself. I also try other ppl’s testnet binaries no luck.

Sent from my iPhone

On 13 Mar 2018, at 12:52 PM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you specify when exactly is the error you are taking about. its almost 10 min video and I don't know what should be looking for.

**Comment by kenken64** [comment]
Oh then on the public test net how can I get coins ? I tried the faucet it didn’t work then some guys from IRC told me to mine myself.

Sent from my iPhone

On 13 Mar 2018, at 1:14 PM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


what do you want to do? You dont need private testnet, to use testnet. Just use public testnet network to play around with monero. In private testnet you will be far behind current monero status. You would have to mine over 1 million blocks to catch up with current monero status, such as having ringct and/or booletproofs.

**Comment by kenken64** [comment]
I am building a simple wallet app for my mobile app so I just need to test rpc calls for balance, fee and transfer

Sent from my iPhone

On 13 Mar 2018, at 1:14 PM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


what do you want to do? You dont need private testnet, to use testnet. Just use public testnet network to play around with monero. In private testnet you will be far behind current monero status. You would have to mine over 1 million blocks to catch up with current monero status, such as having ringct and/or booletproofs.

**Comment by moneroexamples** [comment]
yep, minie youself. Its very easy and fast to mine on testnet. I could send you some test monero, but if you use release monero version you will be on different testnet than I (development testnet version).

**Comment by kenken64** [comment]
Please send me thanks. Also can help me with the mining argument on the public testnet

Sent from my iPhone

On 13 Mar 2018, at 1:20 PM, moneroexamples <notifications@github.com<mailto:notifications@github.com>> wrote:


yep, minie youself. Its very easy and fast to mine on testnet. I could send you, but if you use release monero version you will be on different testnet than I (development testnet version).

**Comment by moneroexamples** [comment]
Just start monero deamon and wallet with `--testnet` flag.

If you provide me with your testnet address and I can sent, but you will be on different chain if you use offical release binaries of monero. So the coins wont appear in your wallet, as you be on different testnet than I.
