### ISSUE TITLE
Is this instruction actual or outdated?

### ISSUE THREAD

**Issue by 0xA01** [moneroexamples/private-testnet#4]
On modern Monero code there are some errors like cumulative difficulty etc. Did you tried to run private testnet recently?

**Comment by 0xA01** [comment]
For example:

`
2018-08-13 21:04:36.246	[P2P1]	WARN 	blockchain.db.lmdb	src/blockchain_db/lmdb/db_lmdb.cpp:75	Attempt to get cumulative difficulty from height 18446744073709551615 failed -- difficulty not in db
`

**Comment by 0xA01** [comment]
start_mining always throws to

`Error: Mining did not start -- BUSY`

**Comment by 0xA01** [comment]
Seems like they fixed testnet to used like main chain?

**Comment by moneroexamples** [comment]
yes. I haven't updated these instructions in years.

Better to use public testnet or stagenet monero networks for playing with xmr.

**Comment by moneroexamples** [comment]
I updated the instructions for latest monero. You can check it out: https://github.com/moneroexamples/private-testnet/blob/master/README.md
