### ISSUE TITLE
Enforce https on moneroexamples/private-testnet

### ISSUE THREAD

**Issue by BigslimVdub** [moneroexamples/private-testnet#5]
Hello,
I noticed this site is not using https unless forced: http://moneroexamples.github.io/private-testnet/
Can you enable https for this: 
<img width="744" alt="enable https" src="https://user-images.githubusercontent.com/30030687/60069167-72393e80-96d7-11e9-9f29-1a6481904ad5.png">

Thank you.

**Comment by moneroexamples** [comment]
Done. 

But can also access github directly: https://github.com/moneroexamples/private-testnet
