### ISSUE TITLE
How do you create coins in private-testnet?

### ISSUE THREAD

**Issue by ghubstan** [moneroexamples/private-testnet#7]
Took a few hours, but finally figured out how to get three nodes running and mining + wallets using `v0.17.2.3`.  
But there are no coins, and no transactions to mine.  Can someone give me a hint about how to create blocks & coins on a private testnet?

I could use public testnet, but prefer private for my use case.

**Comment by meglio** [comment]
@ghubstan what was the solution?

**Comment by dimalinux** [comment]
@meglio The easiest way to test is with a single private node that has the regtest flag turned on or just use the public stagenet which is easy enough to mine on. My guess is that @ghubstan needed to wait for 60 blocks until the mined monero was spendable. You can mine blocks with zero transactions.
